import {
  Activity,
  ArrowLeft,
  ArrowUpRight,
  ArrowUpDown,
  Bell,
  Bookmark,
  Building2,
  CalendarPlus,
  CalendarDays,
  Check,
  ChevronDown,
  CircleCheck,
  Columns3,
  Clock3,
  FileText,
  Headphones,
  GripVertical,
  LayoutGrid,
  ListFilter,
  Mail,
  Map,
  MapPin,
  Menu,
  MoreVertical,
  Palette,
  Plus,
  Search,
  Shield,
  SlidersHorizontal,
  UsersRound,
  X,
  type LucideIcon,
} from "lucide-react";

export const iconMap = {
  activity: Activity,
  arrowLeft: ArrowLeft,
  arrowUpRight: ArrowUpRight,
  sort: ArrowUpDown,
  bell: Bell,
  bookmark: Bookmark,
  building: Building2,
  calendar: CalendarDays,
  calendarPlus: CalendarPlus,
  check: Check,
  chevronDown: ChevronDown,
  circleCheck: CircleCheck,
  columns: Columns3,
  clock: Clock3,
  document: FileText,
  headphones: Headphones,
  move: GripVertical,
  grid: LayoutGrid,
  filter: ListFilter,
  mail: Mail,
  map: Map,
  menu: Menu,
  more: MoreVertical,
  palette: Palette,
  plus: Plus,
  pin: MapPin,
  search: Search,
  shield: Shield,
  sliders: SlidersHorizontal,
  users: UsersRound,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;

export function Icon({ name, size = 19, strokeWidth = 1.75, className }: { name: IconName; size?: number; strokeWidth?: number; className?: string }) {
  const LucideIconComponent = iconMap[name];
  return <LucideIconComponent aria-hidden="true" size={size} strokeWidth={strokeWidth} className={className} />;
}
